### ISSUE TITLE
Only cube shape works

### ISSUE THREAD

**Issue by GaviTSRA** [aurilisdev/Modular-Forcefields#14]
When using any other shape then the cube shape, nothing is created. I may just not know how to set these other shapes up, in which case please tell me!
If you need any more info, im ready to provide it

**Comment by aurilisdev** [comment]
U add shape modules in the slots signifying east west etc. Here u can determine the sizes of the other shapes. Spheres and hemispheres dont care about the direction, and only about the total number of scale upgrades.

**Comment by Rasttny** [comment]
> U add shape modules in the slots signifying east west etc. Here u can determine the sizes of the other shapes. Spheres and hemispheres dont care about the direction, and only about the total number of scale upgrades.
![2024-10-17_02 44 18](https://github.com/user-attachments/assets/3ef8c37b-f8f2-458d-a133-4f2753df15d2)
says it's doing something, doesn't do anything. tried what you said, how you said it, still doesn't work. only visible projectable shape is the cube, if you replace the cube module with a shape, the status indication says its doing something but no forcefield is shown.

**Comment by Rasttny** [comment]
![2024-10-17_02 48 16](https://github.com/user-attachments/assets/8a3e63b5-2f5d-4dba-9d36-833009a5c68e)
![2024-10-17_02 48 07](https://github.com/user-attachments/assets/8e05f986-93e6-4952-b4ac-ce11c5180422)
![2024-10-17_02 48 09](https://github.com/user-attachments/assets/f8e10443-731b-4ac3-9345-925830adccc2)
![2024-10-17_02 48 14](https://github.com/user-attachments/assets/f1034e11-f50f-420d-841e-28cb1f0d601f)


all possible interpretations of what you have said tested above, outcome, no shapes. cube is the only shape that works.
