### ISSUE TITLE
Guide or wiki needed

### ISSUE THREAD

**Issue by Kmek** [aurilisdev/Modular-Forcefields#15]
I've never used any previous MFFS-esque mods so as a new user I have no idea where to start. I saw one youtube video about this mod specifically, but all it did was show how to set up a basic cube in creative mode (explaining nothing the whole time doing so). I don't know what the other upgrades/blocks do or how to use them properly. 

I think that you, as the developer who knows the mod best, should make a guide or wiki explaining how to use your mod to new users. 

What do the blocks do? What do the items do? How do I use them?

It would also be nice if you could add short descriptions of what each block/item does in the tooltip of the items for when you hover over them, so it gives some indication to users when they're trying to figure out stuff in-game.

**Comment by aurilisdev** [comment]
Will be made when we have time

**Comment by aurilisdev** [comment]
Due to another issue i found this again. Wiki was made about a year ago :)
