### ISSUE TITLE
Forcefield doesn't automatically close gaps

### ISSUE THREAD

**Issue by DarkShadow44** [aurilisdev/Modular-Forcefields#4]
Using Modular+Forcefields-1.18.2-0.0.1-2

Per default force fields don't displace blocks. When breaking a block that is part of the "border" of the force field, it doesn't get replaced with a forcefield, leaving a gap instead. For example, when digging below a forcefield, you can safely enter.
IMHO it would be useful if the forcefield automatically closes any gap that opens up by breaking blocks that are part of the forcefield border.

**Comment by aurilisdev** [comment]
Very slow reply but yeah this is performance intensive to implement so is chosen to not happen.
